### ISSUE TITLE
Right handed?

### ISSUE THREAD

**Issue by DasKatzchen** [ZackFreedman/Somatic#1]
How possible would it be to simply mirror the training data and train a right-handed version?

**Comment by ZackFreedman** [comment]
It shouldn’t be necessary. You draw the same letters whether you’re a lefty or a righty.

**Comment by DasKatzchen** [comment]
Now that I'm thinking about it again, you are obviously right. So I would just mirror the relevant 3D printed parts and use the right glove instead of the left. Guess I have a new project for next weekend (This weekend is, obviously, already spoken for)

**Comment by jerrygreen** [comment]
@DieKatzchen I'm pretty sure that requires more than a weekend. Let me guess, - you still didn't make this right-handed version? 😂

**Comment by DasKatzchen** [comment]
I've actually been thinking I should make a display first. Been looking at various OLED screens and mirrors and such.
