### ISSUE TITLE
Missing STL files?

### ISSUE THREAD

**Issue by Trixelit** [ZackFreedman/Somatic#10]
@ZackFreedman The instructable is telling me to print 'Cosmetic plate.stl' which isn't in the repository.

**Comment by ZackFreedman** [comment]
I've added the missing files! The STL's are in millimeters.

------ Original Message ------
From: "Trixelit" ***@***.***>
To: "ZackFreedman/Somatic" ***@***.***>
Cc: "ZackFreedman" ***@***.***>; "Mention" 
***@***.***>
Sent: 4/30/2021 10:20:18 PM
Subject: [ZackFreedman/Somatic] Missing STL files? (#10)

**Comment by Trixelit** [comment]
Thank you!
