### ISSUE TITLE
TensorFlow Lite on Android?

### ISSUE THREAD

**Issue by sudomain** [ZackFreedman/Somatic#3]
Hello. I'm only slightly familiar with the project (it's very cool by the way), but what do you think about moving the TensorFlow Lite model from the Teensy to [an android device](https://www.tensorflow.org/lite/guide/android)? The Teensy 4 chugs aways at 600 MHz, while many mid-grade Android devices are multicored and atleast double the clock speed (my already 3 year old LG clocks at 1.4 GHz). I realize that a phone's bluetooth can't just decide to act as HID device (without root?), so maybe use a process like this?:
1. use bluetooth to take signals from the Somatic, 
2. send to TF lite on android for processing, 
3. send the result back the the Somatic, 
4. have the Somatic send the result as a HID device to whatever it is paired to

I know you said in the video that the Teensy works fine even when underclocked,  but if the tensorflow processing can be moved off device, maybe something smaller than the teensy could be used.

**Comment by ZackFreedman** [comment]
Good idea, but I have no intention to continue working on this project. It's doable, but I'm not going to do it.
