### ISSUE TITLE
STL variants of .f3d file

### ISSUE THREAD

**Issue by noob-master147** [ZackFreedman/Somatic#8]
## It would be really helpful if STL formats of these parts could be made available

![image](https://user-images.githubusercontent.com/43108912/114342545-9f3f3580-9b79-11eb-86b8-1765b1497ddc.png)

**Comment by ZackFreedman** [comment]
All of the STL's are in the STLs directory. There's nothing in the Fusion files that isn't already exported as STL's. I just designed the glove as three models instead of making a separate model for each part.

**Comment by noob-master147** [comment]
got it
thanks a lot 💖
